links = [
    'https://www.marathonbet.ru/su/betting/Football/Portugal/Primeira+Liga+-+43058',
    'https://www.marathonbet.ru/su/betting/Football/England/Premier+League+-+21520',
    'https://www.marathonbet.ru/su/betting/Football/England/Championship+-+22807',
    'https://www.marathonbet.ru/su/betting/Football/Germany/Bundesliga+-+22436',
    'https://www.marathonbet.ru/su/betting/Football/Spain/Primera+Division+-+8736',
    'https://www.marathonbet.ru/su/betting/Football/Italy/Serie+A+-+22434',
    'https://www.marathonbet.ru/su/betting/Football/Netherlands/Eredivisie+-+38090',
    'https://www.marathonbet.ru/su/betting/Football/Portugal/Primeira+Liga+-+43058',
    'https://www.marathonbet.ru/su/betting/Football/Russia/Premier+League+-+22433',
    'https://www.marathonbet.ru/su/betting/Football/Turkey/Super+Lig+-+46180',
    'https://www.marathonbet.ru/su/betting/Football/Russia/Premier+League+-+22433',
    'https://www.marathonbet.ru/su/betting/Football/France/Ligue+1+-+21533',
    'https://www.marathonbet.ru/su/betting/Football/Clubs.+International/UEFA+Champions+League+-+21255',
    'https://www.marathonbet.ru/su/betting/Football/Clubs.+International/UEFA+Europa+League+-+21366',
]
